version: "3.8"
services:
    coursera:
      container_name: 'coursera'
      build: .
      environment:
        TZ: "America/Guayaquil"
        DJANGO_SUPERUSER_USERNAME: root
        DJANGO_SUPERUSER_PASSWORD: root
        DJANGO_SUPERUSER_EMAIL: 'root@email.com'
      ports:
          - "5858:8000"
      volumes:
        - .:/code
      expose:
          - '8000'
      networks:
          - ibm
      deploy:
        resources:
          limits:
            cpus: '0.2'
            memory: 300M
networks:
    ibm:
        driver: bridge